#!/bin/sh

install_for_mac()
{
  EXECUTABLE_NAME=$1
  PACKAGE_NAME=$2
  if command -v $EXECUTABLE_NAME 
  then
    echo "'$PACKAGE_NAME' already installed"
  else
    echo "'$PACKAGE_NAME'..installing"
    brew install $2
  fi
}

install_for_linux()
{
  EXECUTABLE_NAME=$1
  PACKAGE_NAME=$2
  if command -v $EXECUTABLE_NAME 
  then
    echo "'$PACKAGE_NAME' already installed"
  else
    echo "'$PACKAGE_NAME'..installing"
    sudo apt-get -y install $2
  fi
}

# == 1. CLEAN UP

# spin comes with some config files with stow would not override
rm -f ~/.zshrc
rm -f ~/.gitconfig


# == 2. INSTALL STOW

if command -v apt-get &> /dev/null; then
  echo "Detected linux env"
    #                 BINARY PCKG-NAME
    install_for_linux "stow"      "stow"
else
  if command -v brew &> /dev/null; then
    echo "Detected MacOS env"
    install_for_mac "stow" "stow"
  else
    echo "No env detected, dont know how to install packages"
    exit -1
  fi
fi

# == 3. SYMLINK DOTFILES WITH STOW

for folder in `ls ~/dotfiles`
do
    if [ -d "$folder" ]; then
      echo "Linking '$folder'"
      stow -D $folder >/dev/null 2>&1
      stow $folder
    fi
done

# == 4. INSTALL CUSTOM PACKAGES
#
if command -v apt-get &> /dev/null; then
  echo "Detected linux env"
    #                 BINARY PCKG-NAME
    install_for_linux "stow"      "stow"
    install_for_linux "zsh"       "zsh"
    install_for_linux "tmux"      "tmux"
    install_for_linux "autojump"  "autojump"
    install_for_linux "fzy"       "fzy"
    install_for_linux "fdfind"    "fd-find"

    # fix terminfo for ssh with kitty
    ~/.config/kitty/fix_remote_term/install_terminfo.sh
else
  if command -v brew &> /dev/null; then
    echo "Detected MacOS env"
    install_for_mac "stow" "stow"
    install_for_mac "zsh" "zsh"
    install_for_mac "tmux" "tmux"
    install_for_mac "autojump" "autojump"
    install_for_mac "fzy" "fzy"
    install_for_mac "fd" "fd"
    install_for_mac "kitty" "kitty"
  else
    echo "No env detected, dont know how to install packages"
    exit -1
  fi
fi

#https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/JetBrainsMono

# Initialize NeoVim & Packer
mkdir -p ~/.local/share/nvim/site/pack/packer/start
ln -s ~/dotfiles/config/.config/nvim/vendor/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
nvim --headless -c 'so ~/dotfiles/config/.config/nvim/lua/axelerator/packer.lua' -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
